export const COUNTRIES = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan",
  "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia",
  "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada",
  "Cape-Verde", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Congo Democratic", "Congo Republic", "Costa Rica", "Cote D'Ivoire",
  "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "East Timor", "Ecuador",
  "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji", "Finland", "France", "Gabon",
  "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea Bissau", "Guyana",
  "Haiti", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland",
  "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait",
  "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
  "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico",
  "Micronesia Federated", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru",
  "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway", "Oman",
  "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar",
  "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia",
  "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa",
  "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Swaziland", "Sweden", "Switzerland", "Syria",
  "Tajikistan", "Tanzania", "Thailand", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
  "UAE", "Uganda", "Ukraine", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela",
  "Vietnam", "Yemen", "Zambia", "Zimbabwe",
] as const;

export const TOURNAMENT_LOCATIONS = [
  { city: "Katowice", country: "Poland" }, { city: "Cologne", country: "Germany" }, { city: "Berlin", country: "Germany" },
  { city: "Copenhagen", country: "Denmark" }, { city: "Stockholm", country: "Sweden" }, { city: "Malmo", country: "Sweden" },
  { city: "Paris", country: "France" }, { city: "Amsterdam", country: "Netherlands" }, { city: "Brussels", country: "Belgium" },
  { city: "Madrid", country: "Spain" }, { city: "Barcelona", country: "Spain" }, { city: "Lisbon", country: "Portugal" },
  { city: "Milan", country: "Italy" }, { city: "Rome", country: "Italy" }, { city: "London", country: "United Kingdom" },
  { city: "Birmingham", country: "United Kingdom" }, { city: "Helsinki", country: "Finland" }, { city: "Oslo", country: "Norway" },
  { city: "Vienna", country: "Austria" }, { city: "Zurich", country: "Switzerland" }, { city: "Prague", country: "Czech Republic" },
  { city: "Budapest", country: "Hungary" }, { city: "Bucharest", country: "Romania" }, { city: "Sofia", country: "Bulgaria" },
  { city: "Kyiv", country: "Ukraine" }, { city: "Istanbul", country: "Turkey" }, { city: "New York", country: "United States" },
  { city: "Los Angeles", country: "United States" }, { city: "Chicago", country: "United States" }, { city: "Dallas", country: "United States" },
  { city: "Atlanta", country: "United States" }, { city: "Toronto", country: "Canada" }, { city: "Vancouver", country: "Canada" },
  { city: "Mexico City", country: "Mexico" }, { city: "Rio de Janeiro", country: "Brazil" }, { city: "Sao Paulo", country: "Brazil" },
  { city: "Buenos Aires", country: "Argentina" }, { city: "Santiago", country: "Chile" }, { city: "Shanghai", country: "China" },
  { city: "Beijing", country: "China" }, { city: "Shenzhen", country: "China" }, { city: "Seoul", country: "South Korea" },
  { city: "Tokyo", country: "Japan" }, { city: "Osaka", country: "Japan" }, { city: "Singapore", country: "Singapore" },
  { city: "Kuala Lumpur", country: "Malaysia" }, { city: "Bangkok", country: "Thailand" }, { city: "Jakarta", country: "Indonesia" },
  { city: "Mumbai", country: "India" }, { city: "Dubai", country: "UAE" }, { city: "Abu Dhabi", country: "UAE" },
  { city: "Riyadh", country: "Saudi Arabia" }, { city: "Doha", country: "Qatar" }, { city: "Sydney", country: "Australia" },
  { city: "Melbourne", country: "Australia" }, { city: "Auckland", country: "New Zealand" },
] as const;

export const TOURNAMENT_COUNTRIES = Array.from(new Set(TOURNAMENT_LOCATIONS.map(({ country }) => country)));
